# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20171124_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50)),
                ('barco', models.CharField(max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(default='notasviejas', max_length=100)),
                ('sogas', models.BooleanField(default=False)),
                ('pinturas', models.BooleanField(default=False)),
                ('comida', models.BooleanField(default=False)),
                ('tecnico', models.BooleanField(default=False)),
                ('bonded_stores', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('fecha_cotizacion', models.DateTimeField(blank=True, null=True)),
                ('monto_cotizacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_cotizacion', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('socio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_socio', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('lista_de_precio', models.CharField(max_length=50)),
                ('atendido_por', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='followup.Status'),
        ),
        migrations.AddField(
            model_name='cases',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_entrega', to='board.Ubicacion'),
        ),
    ]
