# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='barco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcos_entrega', to='board.Barcos'),
        ),
    ]
