# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_auto_20171124_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='monto_cotizacion',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
