# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_cases_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
    ]
