# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_auto_20171125_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='mv',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cases',
            name='notas',
            field=models.CharField(default='', max_length=100),
        ),
    ]
