# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20171124_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
